CREATE TABLE IF NOT EXISTS "rep_assisted_orders" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "idempotency_key" text NOT NULL,
  "order_id" uuid,
  "invoice_id" uuid,
  "customer_id" uuid,
  "sales_member_id" uuid,
  "created_by_user_id" uuid NOT NULL,
  "status" text DEFAULT 'ready_to_send' NOT NULL,
  "recipient_email" text DEFAULT '' NOT NULL,
  "recipient_phone" text DEFAULT '' NOT NULL,
  "draft_data" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "customer_facing_notes" text,
  "internal_notes" text,
  "purchase_order_number" text,
  "requested_delivery_date" text,
  "shipping_address" text,
  "billing_address" text,
  "access_token_hash" text NOT NULL,
  "access_token_expires_at" timestamp with time zone NOT NULL,
  "access_token_used_at" timestamp with time zone,
  "revoked_at" timestamp with time zone,
  "email_status" text DEFAULT 'pending' NOT NULL,
  "email_sent_at" timestamp with time zone,
  "sms_status" text DEFAULT 'pending' NOT NULL,
  "sms_sent_at" timestamp with time zone,
  "link_opened_at" timestamp with time zone,
  "invoice_viewed_at" timestamp with time zone,
  "payment_completed_at" timestamp with time zone,
  "notification_errors" jsonb DEFAULT '{}'::jsonb NOT NULL,
  "resend_history" jsonb DEFAULT '[]'::jsonb NOT NULL,
  "terms_accepted" boolean DEFAULT false NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "rep_assisted_orders_order_id_unique" UNIQUE("order_id"),
  CONSTRAINT "rep_assisted_orders_invoice_id_unique" UNIQUE("invoice_id"),
  CONSTRAINT "rep_assisted_orders_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade,
  CONSTRAINT "rep_assisted_orders_invoice_id_invoices_id_fk" FOREIGN KEY ("invoice_id") REFERENCES "public"."invoices"("id") ON DELETE cascade,
  CONSTRAINT "rep_assisted_orders_customer_id_customer_accounts_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer_accounts"("id") ON DELETE cascade,
  CONSTRAINT "rep_assisted_orders_sales_member_id_sales_members_id_fk" FOREIGN KEY ("sales_member_id") REFERENCES "public"."sales_members"("id") ON DELETE set null,
  CONSTRAINT "rep_assisted_orders_created_by_user_id_users_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."users"("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "rep_assisted_orders_idempotency_key_idx" ON "rep_assisted_orders" USING btree ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "rep_assisted_orders_access_token_hash_idx" ON "rep_assisted_orders" USING btree ("access_token_hash");
CREATE INDEX IF NOT EXISTS "rep_assisted_orders_sales_member_idx" ON "rep_assisted_orders" USING btree ("sales_member_id", "created_at");
CREATE INDEX IF NOT EXISTS "rep_assisted_orders_customer_idx" ON "rep_assisted_orders" USING btree ("customer_id", "created_at");
