import { randomUUID } from 'crypto'
import { asc, eq, inArray } from 'drizzle-orm'
import { db } from '@/db'
import { customerAccounts, inventoryLocations, products, QUICKBOOKS_SAMPLE_CATEGORIES, users } from '@/db/schema'
import { createSampleRequest } from '@/actions/sample-inventory'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'

const field = 'w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm'
const formAction = createSampleRequest as unknown as (formData: FormData) => Promise<void>
export default async function NewSampleRequestPage() {
  const [locations, productRows, people, customers] = await Promise.all([
    db.select().from(inventoryLocations).where(eq(inventoryLocations.active, true)).orderBy(asc(inventoryLocations.name)),
    db.select().from(products).where(eq(products.active, true)).orderBy(asc(products.name)),
    db.select({ id: users.id, name: users.name }).from(users).where(inArray(users.role, ['admin', 'staff'])).orderBy(asc(users.name)),
    db.select({ id: customerAccounts.id, name: customerAccounts.companyName }).from(customerAccounts).orderBy(asc(customerAccounts.companyName)),
  ])
  return <div className="mx-auto max-w-3xl space-y-5 p-6"><div><h1 className="text-2xl font-bold">New sample request</h1><p className="text-sm text-slate-500">Recipient type and QuickBooks category are intentionally separate.</p></div><Card><CardHeader><CardTitle>Usage details</CardTitle></CardHeader><CardContent><form action={formAction} className="grid gap-4 sm:grid-cols-2"><input type="hidden" name="idempotencyKey" value={randomUUID()}/><Field label="Source location"><select className={field} name="sourceLocationId" required>{locations.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Responsible person"><select className={field} name="responsibleUserId">{people.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Product"><select className={field} name="productId" required>{productRows.map((row) => <option key={row.id} value={row.id}>{row.sku} · {row.name}</option>)}</select></Field><div className="grid grid-cols-2 gap-2"><Field label="Cases"><input className={field} name="quantityCases" type="number" min="0" defaultValue="0"/></Field><Field label="Bottles"><input className={field} name="quantityBottles" type="number" min="0" defaultValue="0"/></Field></div><Field label="Recipient type"><select className={field} name="recipientType" required><option value="customer">Customer</option><option value="prospect">Prospect</option><option value="event">Event</option><option value="charity">Charity</option><option value="internal">Internal</option><option value="other">Other</option></select></Field><Field label="QuickBooks category"><select className={field} name="quickBooksCategory" required>{QUICKBOOKS_SAMPLE_CATEGORIES.map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Recipient / event name"><input className={field} name="recipientName" required/></Field><Field label="Recipient email"><input className={field} name="recipientEmail" type="email"/></Field><Field label="Linked customer (optional)"><select className={field} name="customerAccountId"><option value="">None</option>{customers.map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select></Field><Field label="Recipient details"><input className={field} name="recipientDetails" placeholder="Contact, address, event URL…"/></Field><div className="sm:col-span-2"><Field label="Purpose"><input className={field} name="purpose" required placeholder="What the samples are for"/></Field></div><div className="sm:col-span-2"><Field label="Notes"><textarea className={field} name="notes" rows={3}/></Field></div><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" name="replenishFromWarehouse"/>Automatically create a warehouse replenishment request</label><div className="sm:col-span-2"><Button type="submit">Submit and fulfill request</Button></div></form></CardContent></Card></div>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="space-y-1 text-sm font-medium text-slate-700"><span>{label}</span>{children}</label> }

